language: php

services:
  - postgresql

addons:
  postgresql: "9.6"

# Allows using containers
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache

# Base versions to test raw with the Symfony latest version.
php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - mkdir -p build/logs

install:
  # Database creation
  - psql -c 'create database symfony;' -U postgres
  # Install application
  - composer install --verbose
  # Database oonfiguration
  - cp .env.travis .env
  # Database migration
  - php bin/console doctrine:migrations:migrate -n
  # Data test installation
  - php bin/console doctrine:fixtures:load --env=dev --fixtures=src/DataFixtures -n


# Run script and log coverage in the "build" directory
script:
  # Composer must be validated.
  - composer validate --no-interaction --ansi --verbose
  # Launch server
  - php bin/console server:start
  # Unit test
  - php bin/codecept run unit
  # Functional test
  - php bin/codecept run functional

# After a build, sends a notification to this e-mail with the build results.
notifications:
  email:
    recipients:
      - alexandre.tranchant@gmail.com
    on_success: never
    on_failure: change
